# Generated by Django 5.1.4 on 2025-01-11 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voterrecord',
            old_name='mob_n0',
            new_name='mob_no',
        ),
    ]
