# Generated by Django 5.1.4 on 2025-01-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roll', '0003_alter_voterrecord_mob_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterrecord',
            name='sec_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
