# Generated by Django 4.2 on 2026-06-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roll', '0005_voterrecord_caste_voterrecord_religion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterrecord',
            name='party_choice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
