# Generated by Django 5.1.4 on 2026-06-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roll', '0006_voterrecord_party_choice_voterrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterrecord',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
