# Generated by Django 5.1.4 on 2026-06-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roll', '0008_votergradation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votergradation',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='votergradation',
            name='completed_by',
        ),
        migrations.RemoveField(
            model_name='votergradation',
            name='remarks',
        ),
        migrations.AddField(
            model_name='votergradation',
            name='caste',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='votergradation',
            name='category',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='votergradation',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='votergradation',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='votergradation',
            name='religion',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='votergradation',
            name='traditional',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='votergradation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
