# Generated by Django 5.1.4 on 2026-06-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roll', '0009_remove_votergradation_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='votergradation',
            name='swing_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
