# Generated by Django 5.1.4 on 2026-06-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roll', '0010_votergradation_swing_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterrecord',
            name='category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
